title: Frank Johnson
logo: /assets/img/MLT professional picture.jpeg
description: Greetings! I am a manufacturing engineer, cloud practioner, and DJ that enjoys leveraging data to work at the intersection these fields. Please reach out to me if any of these topics interest you. 
#show downloads: true
theme: jekyll-theme-minimal
